/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ideproyecto;

/**
 *
 * @author Nicolas Ramirez
 */
public class IngresarJF extends javax.swing.JFrame {

    /**
     * Creates new form IngresarJF
     */
    public IngresarJF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbt_registrarse = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtf_correo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtf_contraseña = new javax.swing.JTextField();
        jbt_go = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(270, 410));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setText("¿aún no tienes una cuenta?");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 370, 160, 18);

        jbt_registrarse.setBackground(new java.awt.Color(204, 51, 255));
        jbt_registrarse.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jbt_registrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Registrarse.png"))); // NOI18N
        jbt_registrarse.setBorderPainted(false);
        jbt_registrarse.setContentAreaFilled(false);
        jbt_registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_registrarseActionPerformed(evt);
            }
        });
        jPanel1.add(jbt_registrarse);
        jbt_registrarse.setBounds(80, 330, 120, 45);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Logo LTC.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 10, 150, 190);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel3.setText("correo:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 200, 50, 18);

        jtf_correo.setBackground(new java.awt.Color(153, 255, 255));
        jtf_correo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jtf_correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtf_correoMouseClicked(evt);
            }
        });
        jtf_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_correoActionPerformed(evt);
            }
        });
        jPanel1.add(jtf_correo);
        jtf_correo.setBounds(90, 200, 142, 24);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel4.setText("contraseña:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(18, 230, 70, 18);

        jtf_contraseña.setBackground(new java.awt.Color(153, 255, 255));
        jtf_contraseña.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jtf_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_contraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(jtf_contraseña);
        jtf_contraseña.setBounds(90, 230, 142, 24);

        jbt_go.setBackground(new java.awt.Color(204, 51, 255));
        jbt_go.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jbt_go.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/play1.png"))); // NOI18N
        jbt_go.setToolTipText("");
        jbt_go.setBorderPainted(false);
        jbt_go.setContentAreaFilled(false);
        jbt_go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_goActionPerformed(evt);
            }
        });
        jPanel1.add(jbt_go);
        jbt_go.setBounds(100, 260, 83, 67);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Background_game 1.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 280, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_correoActionPerformed
        
    }//GEN-LAST:event_jtf_correoActionPerformed

    private void jbt_goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_goActionPerformed
        LeccionesJF fra=new LeccionesJF();
        fra.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbt_goActionPerformed

    private void jtf_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_contraseñaActionPerformed

    private void jtf_correoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtf_correoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_correoMouseClicked

    private void jbt_registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_registrarseActionPerformed
        RegistroJF fra=new RegistroJF();
        fra.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbt_registrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbt_go;
    private javax.swing.JButton jbt_registrarse;
    private javax.swing.JTextField jtf_contraseña;
    private javax.swing.JTextField jtf_correo;
    // End of variables declaration//GEN-END:variables
}
