/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ideproyecto;

import java.sql.*;
/**
 *
 * @author Nicolas Ramirez
 */
public class RegistroJF extends javax.swing.JFrame {
    
    int avatarEscogido;

    IDEProyecto conectar = new IDEProyecto();
    Connection cn = conectar.conector();
    
    public RegistroJF() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        correoTxt = new javax.swing.JTextField();
        contrasenaTxt = new javax.swing.JTextField();
        verificarTxt = new javax.swing.JTextField();
        nicknameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botonRegistrar = new javax.swing.JButton();
        botonA1 = new javax.swing.JButton();
        BotonA3 = new javax.swing.JButton();
        botonA2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        botonCondiciones = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setText("registro");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 11, 90, 38);

        correoTxt.setBackground(new java.awt.Color(153, 255, 255));
        correoTxt.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        correoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoTxtActionPerformed(evt);
            }
        });
        jPanel1.add(correoTxt);
        correoTxt.setBounds(134, 55, 123, 24);

        contrasenaTxt.setBackground(new java.awt.Color(153, 255, 255));
        contrasenaTxt.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        contrasenaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaTxtActionPerformed(evt);
            }
        });
        jPanel1.add(contrasenaTxt);
        contrasenaTxt.setBounds(134, 90, 123, 24);

        verificarTxt.setBackground(new java.awt.Color(153, 255, 255));
        verificarTxt.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        verificarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarTxtActionPerformed(evt);
            }
        });
        jPanel1.add(verificarTxt);
        verificarTxt.setBounds(134, 125, 123, 24);

        nicknameTxt.setBackground(new java.awt.Color(153, 255, 255));
        nicknameTxt.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nicknameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicknameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(nicknameTxt);
        nicknameTxt.setBounds(134, 160, 123, 24);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setText("seleccione un avatar:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 195, 116, 18);

        botonRegistrar.setBackground(new java.awt.Color(204, 102, 255));
        botonRegistrar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        botonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/accept.png"))); // NOI18N
        botonRegistrar.setBorderPainted(false);
        botonRegistrar.setContentAreaFilled(false);
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(botonRegistrar);
        botonRegistrar.setBounds(190, 330, 60, 60);

        botonA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Avatar1.png"))); // NOI18N
        botonA1.setBorder(null);
        botonA1.setBorderPainted(false);
        botonA1.setContentAreaFilled(false);
        botonA1.setFocusPainted(false);
        botonA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonA1);
        botonA1.setBounds(10, 281, 72, 37);

        BotonA3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Avatar3.png"))); // NOI18N
        BotonA3.setBorder(null);
        BotonA3.setBorderPainted(false);
        BotonA3.setContentAreaFilled(false);
        BotonA3.setFocusPainted(false);
        BotonA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonA3ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonA3);
        BotonA3.setBounds(171, 281, 72, 37);

        botonA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Avatar2.png"))); // NOI18N
        botonA2.setBorder(null);
        botonA2.setBorderPainted(false);
        botonA2.setContentAreaFilled(false);
        botonA2.setFocusPainted(false);
        botonA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonA2ActionPerformed(evt);
            }
        });
        jPanel1.add(botonA2);
        botonA2.setBounds(88, 281, 72, 37);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/avataaars 2.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 219, 52, 56);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/avataaars 1.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 219, 52, 56);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/avataaars 3.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(187, 219, 52, 56);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel6.setText("correo");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 58, 36, 18);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel7.setText("contraseña");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 93, 60, 18);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel8.setText("verificar contraseña");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 128, 114, 18);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel9.setText("nickname ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 166, 70, 17);

        botonCondiciones.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        botonCondiciones.setMnemonic('a');
        botonCondiciones.setText("acepto los terminos de uso");
        botonCondiciones.setContentAreaFilled(false);
        botonCondiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCondicionesActionPerformed(evt);
            }
        });
        jPanel1.add(botonCondiciones);
        botonCondiciones.setBounds(10, 340, 159, 25);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Background_game 1.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 280, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void correoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoTxtActionPerformed

    private void contrasenaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenaTxtActionPerformed

    private void verificarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verificarTxtActionPerformed

    private void nicknameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicknameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicknameTxtActionPerformed

    private void botonA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA1ActionPerformed
        // TODO add your handling code here:
        avatarEscogido = 1; 
    }//GEN-LAST:event_botonA1ActionPerformed

    private void BotonA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonA3ActionPerformed
        // TODO add your handling code here:
        avatarEscogido = 3;         
        
    }//GEN-LAST:event_BotonA3ActionPerformed

    private void botonA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonA2ActionPerformed
        // TODO add your handling code here:
        avatarEscogido = 2; 
    }//GEN-LAST:event_botonA2ActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        try{
            PreparedStatement pst = cn.prepareStatement("INSERT INTO nino (correo, contrasena, nicname, saldo, avatar) VALUES (?,?,?,?,?)");
            pst.setString(1, correoTxt.getText());
            pst.setString(2, contrasenaTxt.getText());
            pst.setString(3, nicknameTxt.getText());
            pst.setInt(4, 0);
            pst.setInt(5, avatarEscogido);
            pst.executeUpdate();
            
            
            
        }
        catch(Exception e){
            System.out.println(e);
            
        }
        LeccionesJF fra=new LeccionesJF();
        fra.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void botonCondicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCondicionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCondicionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonA3;
    private javax.swing.JButton botonA1;
    private javax.swing.JButton botonA2;
    private javax.swing.JRadioButton botonCondiciones;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JTextField contrasenaTxt;
    private javax.swing.JTextField correoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nicknameTxt;
    private javax.swing.JTextField verificarTxt;
    // End of variables declaration//GEN-END:variables
}
